### ISSUE TITLE
automatically clean up a failed apply upgrade

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#119]
The solution overview should get a feature to clean up a failed apply upgrade.

### ToDos
- [ ] add button to grid cell
- [ ] delete holding solution from target environment
- [ ] renew export
- [ ] start new import
