### ISSUE TITLE
delete patch

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#132]
It should be possible to delete a patch. This is then removed from Power CID Portal and from the development environment. This is only possible as long as no successful import has taken place anywhere. The patch should be displayed as crossed out in the solution overview.

### ToDos
- [ ] HTTP Delete for Patch Controller
- [ ] add delete icon to solution overview
- [ ] cross out deleted patch
- [ ] disable action icons of deleted patch
