### ISSUE TITLE
delete application

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#146]
An application should be able to be deleted from Power CID so that it is no longer displayed in the overviews. 

### ToDos
- [ ] add field "deleted" to model of Application
- [ ] add button to application overview for deleting
- [ ] filter application overview, dropdown of solution overview etc. for non-deleted applications
