### ISSUE TITLE
changeover to delegated permissions

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#166]
The application should use delegated rights only. Application permissions are switched and revoked. 

### ToDos
- [x] Change Azure AD permissions
- [x] Switch to API requests in user context
- [x] Detection of application owner
- [x] Onboarding new tenants
- [x] Documentation of changes and instructions to existing users
