### ISSUE TITLE
grouping of applications

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#167]
Each application should get a property "Group". Data type "Group" is to be checked (free text, entity, ...). In the soltion overview there are two dropdowns to select the entity. The first dropdown is for selecting the group, the second one is for selecting the application within the group.

### ToDos
- [ ] Add "Group" to Application
- [ ] UI feature to set/edit group of Application
- [ ] Edit Solution Overview Dropdown(s)
- [ ] Group Applications by group in Applications Component
