### ISSUE TITLE
performance optimisations

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#199]
Landing procedures within the applications are to be shortened. 

### ToDos
- [ ] prevent duplicate requests
- [ ] reduce response size
- [ ] prevent unnecessary requests

**Comment by FGiesche** [comment]
https://atprod.crm4.dynamics.com/main.aspx?appid=a325de3c-cfa0-ea11-a812-000d3ad8b0a4&pagetype=entityrecord&etn=incident&id=8b53eee5-9ccc-ee11-9078-0022489c55da
