### ISSUE TITLE
create user manual

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#20]
A user manuel for Power CID Portal shall be created. All import information for using the application should be descripted in way that everyone can use the Portal without additional instruction. This includes all roles (user, manager & admin).

### ToDos
- [ ] develop structure of the document
- [ ] write the user manual
- [ ] include screenshots where it makes sense

**Comment by FGiesche** [comment]
Potential edit by at MA ced

**Comment by FGiesche** [comment]
Include sample Security Role for Power CID Portal application user with all commonly needed privileges.
