### ISSUE TITLE
define manual test process

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#24]
A manual test process shall be defined. The defined test process shall be run through for every release.

### ToDos
- [ ] identify important features or functionalities
- [ ] document the sequence of a possible manual test
- [ ] instruct test persons (at Service)
