### ISSUE TITLE
read the current status of existing applications

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#26]
During adding an existing application it current status on all environments shall be read and saved as action in the database.

### ToDos
- [ ] read in all existing applications of the development environment at once in Application Component
- [ ] background process: query/save meta information, existing patches, delivery status
- [ ] do not create an initial upgrade
- [ ] after completion of the background process: display in the Solution Overview shows the status
