### ISSUE TITLE
Deactivate environment

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#269]
It should be possible for users to deactivate environments that are no longer used and that may have already been deleted in the data vault. They will then no longer appear in the environment overview and when configuring the deployment paths.

### ToDos
- [ ] add Button in environment overview
- [ ] prevent deactivation if environment is used in deployment path
- [ ] show only non-deactive environments in overview and deployment path configuration
- [ ] check if environment MS Id is used as identifiery on environment sync
