### ISSUE TITLE
Refactoring add application user to environment

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#270]
Die Möglichkeit zur Anlage und Rechtevergabe des Anwendungsbenutzers soll über die Umgebungsübersicht möglich sein. Eine Auswahl der Umgebungen gibt an für welche Umgebungen diese Aktion durchgeführt werden soll. 

### ToDos
- [ ] add selection to environment overview
- [ ] add input to action
- [ ] remove feature from settings component
