### ISSUE TITLE
improvements during create and assign application user

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#28]
The creation and assignment of the application user through the Power CID Portal shall be improved.

### ToDos
- [ ] introduce missing progress bar, due to very long loading time 
- [ ] log window too small, no scrolling available
- [ ] error (role assignment) not understandable 
- [ ] make log downloadable

**Comment by FGiesche** [comment]
https://atprod.crm4.dynamics.com/main.aspx?appid=a325de3c-cfa0-ea11-a812-000d3ad8b0a4&pagetype=entityrecord&etn=incident&id=2ba781f5-08ef-ed11-8849-0022489bf799
