### ISSUE TITLE
cancel import

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#43]
An import shall be able to be canceled. This shall only affects a non-started-in-environment import.

### ToDos
- [ ] add icon to Solution Overview card
- [ ] delete async job
- [ ] set action result 2, status 3 with cancalation message
