### ISSUE TITLE
reliable start of Import

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#67]
An import should be triggered reliably on the target system. Only when it has been ensured that the import is running, the status should change to "in progress".

### ToDos
- [ ] check solution history on target system
- [ ] set "in progress" if is running
- [ ] retry start if is not running

**Comment by FGiesche** [comment]
bug can not be reproduced anymore
