### ISSUE TITLE
deployment details for import action

### ISSUE THREAD

**Issue by FGiesche** [appliedtechnologies/PowerCIDPortal#92]
Deployment details should be saved for each import action. These should document, for example, the environment variables and connection references used during delivery.

### ToDos
- [x] extend data model (add textfield to action)
- [x] save details during import
- [x] show details in Action Details component
