### ISSUE TITLE
new grids for environment variables

### ISSUE THREAD

**Issue by chadapptech** [appliedtechnologies/PowerCIDPortal#95]
A view is to be created in which all environment variables of an environment are displayed with display name, name, type, default value and current value.

### ToDos
- [x] Add new TypeScript service class 
- [x] Add method in TypScript service: make two authenticated calls to the Dataverse API to retrieve environmentvariabledefinitions and environmentvariablevalues of an environment defined by MS Id (due 13.06.23,  4 hours)
- [ ] Create model class for merged data (due ??, 1 hour)
- [ ]  Add method in TypScript service: Merge return values environmentvariabledefinitions and environmentvariablevalues into an array (due ??, 4 hours)
- [ ] Add menu item "Environment Variables" to the first level of the main menu with matching icon (due ??, 2 hours)
- [ ] Create Angular component, connect with menu item and routing ("/variables") (due ??, 4 hours)
- [ ] Calling the portal API via existing (?) TypeScript service method to query the stored environments (due ??, 2 hours)
- [ ] Display of a DevExtreme dropdown with the queried environments (due ??, 2 hours)
- [ ] After selecting an environment in the dropdown, call methods to query and merge the respective environment variables (due ??, 2 hours)
- [ ] Display a DevExtreme data grid, with the columns see issue description (due ??, 8 hours)

**Comment by FGiesche** [comment]
gerade einen neuen commit mit aktualisierter icon font hinzugefügt, für das Menü-Icon sollte powercid-icon-variable genutzt werden
